sudo: required
services:
  - docker
language: java
jdk:
  - openjdk8
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - if [ ! -z "$TRAVIS_TAG" ]; then
      docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
      ./gradlew shadowJar generateVersionFile ;
      docker build --build-arg VERSION=$(cat version.txt) -t "kmruiz/feaggle-server:$(cat version.txt)" . ;
      docker push "kmruiz/feaggle-server:$(cat version.txt)" ;
    fi